import type { Outcome, Profile, StarChange } from './profile'
import { MAX_STARS, totalStars, venuesCleared } from './stages'

export interface AchievementContext {
  profile: Profile
  outcome: Outcome
  now: Date
  stars?: StarChange
}

export type AchievementGroup = 'Getting started' | 'Skill' | 'Technique' | 'Collection' | 'Habits' | 'Party' | 'Secret'

export interface Achievement {
  id: string
  emoji: string
  title: string
  description: string
  xp: number
  group: AchievementGroup
  /** Shown as ??? until unlocked. */
  hidden?: boolean
  progress?: (profile: Profile) => [number, number]
  test: (context: AchievementContext) => boolean
}

/** An achievement for reaching a number the profile keeps track of. */
function milestone(value: (profile: Profile) => number, target: number): Pick<Achievement, 'progress' | 'test'> {
  return {
    progress: (profile) => [Math.min(value(profile), target), target],
    test: ({ profile }) => value(profile) >= target,
  }
}

function perfectEvent(minFaces: number) {
  return ({ outcome }: AchievementContext) =>
    outcome.kind === 'event' && outcome.score.perfect && outcome.answers.length >= minFaces
}

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first-event',
    emoji: '🤝',
    title: 'Nice to Meet You',
    description: 'Finish your first event.',
    xp: 25,
    group: 'Getting started',
    ...milestone((profile) => profile.stats.events, 1),
  },
  {
    id: 'venue-1',
    emoji: '🏁',
    title: 'Regular',
    description: 'Beat the boss of your first venue.',
    xp: 25,
    group: 'Getting started',
    ...milestone((profile) => venuesCleared(profile.stages), 1),
  },
  {
    id: 'stars-30',
    emoji: '⭐',
    title: 'Rising Star',
    description: 'Collect 30 stars on the Social Circuit.',
    xp: 50,
    group: 'Getting started',
    ...milestone((profile) => totalStars(profile.stages), 30),
  },
  {
    id: 'venue-4',
    emoji: '🗺️',
    title: 'Circuit Veteran',
    description: 'Beat the bosses of 4 venues.',
    xp: 50,
    group: 'Getting started',
    ...milestone((profile) => venuesCleared(profile.stages), 4),
  },
  {
    id: 'venue-7',
    emoji: '👑',
    title: 'Champion',
    description: 'Win the Grand Final of the Memory Championship.',
    xp: 100,
    group: 'Getting started',
    ...milestone((profile) => venuesCleared(profile.stages), 7),
  },
  {
    id: 'stars-all',
    emoji: '🌌',
    title: 'Constellation',
    description: 'Collect every star on the Social Circuit.',
    xp: 100,
    group: 'Getting started',
    ...milestone((profile) => totalStars(profile.stages), MAX_STARS),
  },
  {
    id: 'perfect-5',
    emoji: '🎯',
    title: 'Total Recall',
    description: 'Get every name right in an event with 5 or more faces.',
    xp: 25,
    group: 'Skill',
    test: perfectEvent(5),
  },
  {
    id: 'perfect-10',
    emoji: '💎',
    title: 'Flawless Host',
    description: 'A perfect event with 10 or more faces.',
    xp: 50,
    group: 'Skill',
    test: perfectEvent(10),
  },
  {
    id: 'perfect-20',
    emoji: '🧠',
    title: 'Photographic',
    description: 'A perfect event with 20 or more faces.',
    xp: 100,
    group: 'Skill',
    test: perfectEvent(20),
  },
  {
    id: 'combo-5',
    emoji: '🔥',
    title: 'On a Roll',
    description: 'Reach a 5-name combo.',
    xp: 25,
    group: 'Skill',
    ...milestone((profile) => profile.stats.bestCombo, 5),
  },
  {
    id: 'combo-10',
    emoji: '⚡',
    title: 'Unstoppable',
    description: 'Reach a 10-name combo.',
    xp: 50,
    group: 'Skill',
    ...milestone((profile) => profile.stats.bestCombo, 10),
  },
  {
    id: 'combo-20',
    emoji: '🤖',
    title: 'Name Machine',
    description: 'Reach a 20-name combo.',
    xp: 100,
    group: 'Skill',
    ...milestone((profile) => profile.stats.bestCombo, 20),
  },
  {
    id: 'lightning-25',
    emoji: '⏱️',
    title: 'Quick Draw',
    description: 'Give 25 lightning-fast answers.',
    xp: 25,
    group: 'Skill',
    ...milestone((profile) => profile.stats.lightning, 25),
  },
  {
    id: 'rare-perfect',
    emoji: '🦜',
    title: 'Rare Bird',
    description: 'A perfect event with rare names and 6 or more faces.',
    xp: 50,
    group: 'Skill',
    test: (context) =>
      perfectEvent(6)(context) && context.outcome.kind === 'event' && context.outcome.event.rules.namePool === 'extended',
  },
  {
    id: 'hintless',
    emoji: '🚲',
    title: 'No Training Wheels',
    description: 'Earn 3 stars in a stage with hints off.',
    xp: 50,
    group: 'Skill',
    test: ({ outcome, stars }) => outcome.kind === 'event' && !outcome.hints && stars?.earned === 3,
  },
  {
    id: 'confident',
    emoji: '😎',
    title: 'Confident',
    description: 'Earn the quick-study bonus on 5 names in one event.',
    xp: 25,
    group: 'Skill',
    test: ({ outcome }) =>
      outcome.kind === 'event' && outcome.score.answers.filter((item) => item.quick > 0).length >= 5,
  },
  {
    id: 'anchors-25',
    emoji: '📍',
    title: 'Feature Spotter',
    description: 'Anchor 25 faces by tapping a feature.',
    xp: 25,
    group: 'Technique',
    ...milestone((profile) => profile.stats.anchors, 25),
  },
  {
    id: 'anchors-150',
    emoji: '🔍',
    title: 'Face Reader',
    description: 'Anchor 150 faces.',
    xp: 50,
    group: 'Technique',
    ...milestone((profile) => profile.stats.anchors, 150),
  },
  {
    id: 'proof',
    emoji: '📈',
    title: 'Proof Positive',
    description: 'Remember at least 80% of the faces you anchor (after 20 anchors).',
    xp: 50,
    group: 'Technique',
    progress: (profile) => [Math.min(profile.stats.anchored.total, 20), 20],
    test: ({ profile: { stats } }) => stats.anchored.total >= 20 && stats.anchored.hits / stats.anchored.total >= 0.8,
  },
  {
    id: 'vips-5',
    emoji: '🌟',
    title: 'Red Carpet',
    description: 'Name 5 VIP guests.',
    xp: 25,
    group: 'Technique',
    ...milestone((profile) => profile.stats.vips, 5),
  },
  {
    id: 'small-talk',
    emoji: '🗣️',
    title: 'Small Talker',
    description: 'Earn 3 stars in a stage with small talk.',
    xp: 50,
    group: 'Technique',
    test: ({ outcome, stars }) => outcome.kind === 'event' && outcome.event.rules.smallTalk > 0 && stars?.earned === 3,
  },
  {
    id: 'sprint-2000',
    emoji: '🎨',
    title: 'Imagination Gym',
    description: 'Score 2,000 in Picture Sprint.',
    xp: 25,
    group: 'Technique',
    ...milestone((profile) => profile.stats.sprintBest, 2000),
  },
  {
    id: 'sprint-4000',
    emoji: '🏅',
    title: 'Image Athlete',
    description: 'Score 4,000 in Picture Sprint.',
    xp: 50,
    group: 'Technique',
    ...milestone((profile) => profile.stats.sprintBest, 4000),
  },
  {
    id: 'names-50',
    emoji: '🦋',
    title: 'Social Butterfly',
    description: 'Remember 50 names.',
    xp: 25,
    group: 'Collection',
    ...milestone((profile) => profile.stats.names, 50),
  },
  {
    id: 'names-250',
    emoji: '📇',
    title: 'Name Collector',
    description: 'Remember 250 names.',
    xp: 50,
    group: 'Collection',
    ...milestone((profile) => profile.stats.names, 250),
  },
  {
    id: 'names-1000',
    emoji: '📚',
    title: 'Walking Directory',
    description: 'Remember 1,000 names.',
    xp: 100,
    group: 'Collection',
    ...milestone((profile) => profile.stats.names, 1000),
  },
  {
    id: 'contacts-25',
    emoji: '📒',
    title: 'Little Black Book',
    description: 'Make 25 contacts.',
    xp: 25,
    group: 'Collection',
    ...milestone((profile) => profile.stats.contacts, 25),
  },
  {
    id: 'contacts-100',
    emoji: '🗂️',
    title: 'Rolodex',
    description: 'Make 100 contacts.',
    xp: 50,
    group: 'Collection',
    ...milestone((profile) => profile.stats.contacts, 100),
  },
  {
    id: 'reunion-1',
    emoji: '👋',
    title: 'Long Time No See',
    description: 'Finish your first reunion.',
    xp: 25,
    group: 'Collection',
    ...milestone((profile) => profile.stats.reunions, 1),
  },
  {
    id: 'reunion-10',
    emoji: '🤗',
    title: 'Old Friends',
    description: 'Finish 10 reunions.',
    xp: 50,
    group: 'Collection',
    ...milestone((profile) => profile.stats.reunions, 10),
  },
  {
    id: 'lifelong',
    emoji: '💛',
    title: 'Lifelong Friend',
    description: 'Bring a contact all the way to the Lifelong tier.',
    xp: 100,
    group: 'Collection',
    ...milestone((profile) => profile.stats.lifelong, 1),
  },
  {
    id: 'streak-3',
    emoji: '📅',
    title: 'Warming Up',
    description: 'Train 3 days in a row.',
    xp: 25,
    group: 'Habits',
    ...milestone((profile) => profile.streak.best, 3),
  },
  {
    id: 'streak-7',
    emoji: '🗓️',
    title: 'Habit Formed',
    description: 'Train 7 days in a row.',
    xp: 50,
    group: 'Habits',
    ...milestone((profile) => profile.streak.best, 7),
  },
  {
    id: 'streak-30',
    emoji: '🏆',
    title: 'Unforgettable',
    description: 'Train 30 days in a row.',
    xp: 100,
    group: 'Habits',
    ...milestone((profile) => profile.streak.best, 30),
  },
  {
    id: 'daily-1',
    emoji: '🎟️',
    title: 'Event of the Day',
    description: 'Finish a Daily Event.',
    xp: 25,
    group: 'Habits',
    ...milestone((profile) => profile.stats.dailies, 1),
  },
  {
    id: 'daily-10',
    emoji: '🎫',
    title: 'Regular Guest',
    description: 'Finish 10 Daily Events.',
    xp: 50,
    group: 'Habits',
    ...milestone((profile) => profile.stats.dailies, 10),
  },
  {
    id: 'quests-all',
    emoji: '🐝',
    title: 'Busy Bee',
    description: 'Complete all daily quests in one day.',
    xp: 25,
    group: 'Habits',
    ...milestone((profile) => profile.stats.questDays, 1),
  },
  {
    id: 'party-5',
    emoji: '🎉',
    title: 'Life of the Party',
    description: 'Survive 5 waves in Endless Party.',
    xp: 25,
    group: 'Party',
    ...milestone((profile) => profile.stats.partyBestWaves, 5),
  },
  {
    id: 'party-10',
    emoji: '🎊',
    title: 'Party Legend',
    description: 'Survive 10 waves in Endless Party.',
    xp: 50,
    group: 'Party',
    ...milestone((profile) => profile.stats.partyBestWaves, 10),
  },
  {
    id: 'party-guests',
    emoji: '🏠',
    title: 'Full House',
    description: 'Meet 25 guests in a single party.',
    xp: 50,
    group: 'Party',
    ...milestone((profile) => profile.stats.partyBestGuests, 25),
  },
  {
    id: 'night-owl',
    emoji: '🦉',
    title: 'Night Owl',
    description: 'Train between midnight and 5 am.',
    xp: 25,
    group: 'Secret',
    hidden: true,
    test: ({ now }) => now.getHours() < 5,
  },
  {
    id: 'early-bird',
    emoji: '🐦',
    title: 'Early Bird',
    description: 'Train between 5 and 8 am.',
    xp: 25,
    group: 'Secret',
    hidden: true,
    test: ({ now }) => now.getHours() >= 5 && now.getHours() < 8,
  },
  {
    id: 'comeback',
    emoji: '💪',
    title: 'Comeback Kid',
    description: 'Earn 3 stars in a stage you once failed.',
    xp: 50,
    group: 'Secret',
    hidden: true,
    test: ({ stars }) => Boolean(stars?.failedBefore) && stars?.earned === 3,
  },
  {
    id: 'deja-vu',
    emoji: '🔁',
    title: 'Déjà Vu',
    description: 'Practice the same faces again and get them all right.',
    xp: 25,
    group: 'Secret',
    hidden: true,
    test: ({ outcome }) => outcome.kind === 'event' && outcome.retry && outcome.score.perfect,
  },
  {
    id: 'smart-10',
    emoji: '🧩',
    title: 'Adaptive Ace',
    description: 'Reach Smart level 10 in Free Practice.',
    xp: 50,
    group: 'Secret',
    hidden: true,
    ...milestone((profile) => profile.smartLevel, 10),
  },
]

export function evaluateAchievements(context: AchievementContext): Achievement[] {
  return ACHIEVEMENTS.filter((achievement) => !context.profile.achievements[achievement.id] && achievement.test(context))
}
